name: Test on Ubuntu
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Test
        run: >-
          gem --version
          gem install kramdown
